version: '3'

services:
  hello:
    container_name: hello_test_container
    image: hello-world
    networks:
      - test_net
      
  yaksha_app:
    container_name: yaksha_test_container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test_net

networks:
  test_net:
    name: test_net
